<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>plugin</artifactId>
    <version>6.2138.v03274d462c13</version>
    <relativePath />
  </parent>

  <groupId>io.jenkins.plugins</groupId>
  <artifactId>cursor-origin-branch-source</artifactId>
  <version>${revision}${changelist}</version>
  <packaging>hpi</packaging>

  <name>Cursor Origin Branch Source Plugin</name>
  <url>https://github.com/jenkinsci/${project.artifactId}-plugin</url>
  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/license/mit/</url>
    </license>
  </licenses>
  <scm child.scm.connection.inherit.append.path="false" child.scm.developerConnection.inherit.append.path="false" child.scm.url.inherit.append.path="false">
    <connection>scm:git:https://github.com/${gitHubRepo}</connection>
    <developerConnection>scm:git:https://github.com/${gitHubRepo}</developerConnection>
    <tag>${scmTag}</tag>
    <url>https://github.com/${gitHubRepo}</url>
  </scm>

  <properties>
    <revision>1.0</revision>
    <changelist>-SNAPSHOT</changelist>
    <!-- https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ -->
    <jenkins.baseline>2.568</jenkins.baseline>
    <jenkins.version>${jenkins.baseline}.1</jenkins.version>
    <gitHubRepo>jenkinsci/${project.artifactId}-plugin</gitHubRepo>
    <spotless.check.skip>false</spotless.check.skip>
    <ban-junit4-imports.skip>false</ban-junit4-imports.skip>
    <ban-commons-lang-2.skip>false</ban-commons-lang-2.skip>
    <hpi.strictBundledArtifacts>true</hpi.strictBundledArtifacts>
    <hpi.bundledArtifacts>jackson-databind-nullable</hpi.bundledArtifacts>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.jenkins.tools.bom</groupId>
        <artifactId>bom-${jenkins.baseline}.x</artifactId>
        <version>6931.vea_a_b_c6fd017d</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.jenkins.plugins</groupId>
      <artifactId>jackson3-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>branch-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
      <version>0.2.11</version>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>annotations</artifactId>
      <version>3.0.1</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <plugins>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>7.25.0</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <!-- https://cursor.com/docs/api/origin/openapi.yaml -->
              <inputSpec>${project.basedir}/src/main/resources/origin-openapi.yaml</inputSpec>
              <generatorName>java</generatorName>
              <library>native</library>
              <!-- TODO -attribute paths.'/v1/origin/repos/{identifier.ownerSlug}/{identifier.name}/git/matching-refs/{ref}'(get).operationId is repeated -->
              <skipValidateSpec>true</skipValidateSpec>
              <generateApiTests>false</generateApiTests>
              <generateApiDocumentation>false</generateApiDocumentation>
              <generateModelTests>false</generateModelTests>
              <generateModelDocumentation>false</generateModelDocumentation>
              <apiPackage>io.jenkins.plugins.cursor_origin_branch_source.origin_openapi.api</apiPackage>
              <modelPackage>io.jenkins.plugins.cursor_origin_branch_source.origin_openapi.model</modelPackage>
              <!-- https://github.com/OpenAPITools/openapi-generator/issues/5800 -->
              <supportingFilesToGenerate>ApiResponse.java,ProgressResponseBody.java,GzipRequestInterceptor.java,ProgressRequestBody.java,JSON.java,ServerVariable.java,StringUtil.java,Configuration.java,ApiClient.java,ApiCallback.java,ServerConfiguration.java,ApiException.java,Pair.java,ApiKeyAuth.java,HttpBasicAuth.java,HttpBearerAuth.java,Authentication.java,RFC3339JavaTimeModule.java,RFC3339DateFormat.java,RFC3339InstantDeserializer.java</supportingFilesToGenerate>
              <configOptions>
                <sourceFolder>.</sourceFolder>
                <useJackson3>true</useJackson3>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
